#!/usr/bin/python3 

import csv
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.impute import SimpleImputer as ip

dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,3].values
imputer=ip(missing_values='nan',strategy='mean')
imputer=imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)
